pref("extensions.procon.currentVersion", "0.0");
pref("extensions.procon.blacklist.enabled", true);
pref("extensions.procon.blacklist.sites.enabled", true);
pref("extensions.procon.blacklist.words.enabled", true);
pref("extensions.procon.blacklist.sites", "xxx\nporn\nplayboy\nxhamster\ntwerk\njiggle\nnsfw\ntblop\nxvideo\nredtube\ngonewild\nbeastiality\nmilf\nfuck\npussy\nblowjob\nhardcore\ncumshot\nhentai");
pref("extensions.procon.blacklist.words", "18 U.S.C\n18 USC 2257\nexplicit photos\namateur photos\namateur videos\nadult material\nxxx video\nxxx-rated\nsexually explicit\nadult only\nadults only\nsexually explicit material\nhentai\nadult web\nerotic\nfree sex\nadult movie\nadults movie\nblow job\nblowjob\ncock suck\nsexiest videos\nporndirectory\nsoftcore\nsoft-core\nsoftporn\nsoft-porn\nat least 18 years\n18.*2257\n2257.*information\n2257.*notice\n2257.*statement\nusc2257\nanime.*xxx");
pref("extensions.procon.blacklist.advanced.renderDelay", false);
pref("extensions.procon.blacklist.advanced.redirect", false);
pref("extensions.procon.blacklist.advanced.redirectURL", "");
pref("extensions.procon.blacklist.advanced.limitNetAccess", false);
pref("extensions.procon.blacklist.advanced.customWarning", false);
pref("extensions.procon.blacklist.advanced.customWarningMsg", "");
pref("extensions.procon.blacklist.advanced.showDetails", false);
pref("extensions.procon.whitelist.enabled", true);
pref("extensions.procon.whitelist.sites", "mozilla.org\nreddit.com/r/nofap");
pref("extensions.procon.profanitylist.enabled", true);
pref("extensions.procon.profanitylist.placeholder", "!@#$%^&*");
pref("extensions.procon.profanitylist.words", "Pussy\nJackass\nGoddamn\nBitchy\nBitched\nBitching\nAss hole\nTits\nTit\nPussy\nDamnit\nBastard\nCunt\nDickhead\nBallsack\nass\nFaggot\nNiggaz\nNigger\nNigga\nLmao\nLmfao\nShit\nCunt\nAsshole\nAss-hole\nMotherfucker\nFucker\nFuck\nBitches\nBitch\nDamn");
pref("extensions.procon.subscriptions.enabled", false);
pref("extensions.procon.subscriptions.urls", '["http%3A%2F%2Fhpaolini.com%2Fsubscriptions%2Fprofanity_en-US.txt"]');
pref("extensions.procon.subscriptions.blacklist.words", "{}");
pref("extensions.procon.subscriptions.blacklist.sites", "{}");
pref("extensions.procon.subscriptions.whitelist.sites", "{}");
pref("extensions.procon.subscriptions.profanitylist.words", "{}");
pref("extensions.procon.subscriptions.lastUpdateTime", 0);
